{
 "title": "Big Dashboard",
 "tags": [ "demo" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Memory / CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "alias(movingAverage(scaleToSeconds(seriesByTag('name=request_status.count', 'status=code_302', 'app=fakesite', 'server=web_server_01'), 10), 20, 0), 'cpu')"
    },
    {
     "target": "alias(seriesByTag('name=statsd.counters.session_start', 'app=fakesite', 'device=desktop'), 'memory')"
    }
   ]
  },
  {
   "title": "logins",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(movingAverage(scaleToSeconds(seriesByTag('name=requests.count', 'app=fakesite', 'server=web_server_01'), 1), 2, 0), 'logins')"
    },
    {
     "target": "alias(movingAverage(timeShift(scaleToSeconds(seriesByTag('name=requests.count', 'app=fakesite', 'server=web_server_01'), 1), '1h'), 2, 0), 'logins (-1 hour)')"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "format": "bytes",
   "valueName": "avg",
   "targets": [
    {
     "target": "scale(seriesByTag('app=backend', 'server=backend_01', 'name=requests.count'), 0.4)"
    }
   ]
  },
  {
   "title": "Sign ups",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "seriesByTag('app=backend', 'server=backend_02', 'name=requests.count')"
    }
   ]
  },
  {
   "title": "Sign outs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "seriesByTag('name=requests.count', 'app=backend', 'server=backend_04')"
    }
   ]
  },
  {
   "title": "Logins",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "scale(seriesByTag('name=requests.count', 'app=backend', 'server=backend_01'), 0.7)"
    }
   ]
  },
  {
   "title": "server requests",
   "type": "graph",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByTags(movingAverage(scaleToSeconds(seriesByTag('name=requests.count', 'app=fakesite', 'target='), 1), 2, 0), 'server')"
    }
   ]
  },
  {
   "title": "Logouts",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "scale(seriesByTag('name=requests.count', 'app=backend', 'server=backend_01'), 0.8)"
    }
   ]
  },
  {
   "title": "Support calls",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "scale(seriesByTag('name=requests.count', 'app=backend', 'server=backend_03'), 0.3)"
    }
   ]
  },
  {
   "title": "Google hits",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "scale(seriesByTag('name=requests.count', 'app=backend', 'server=backend_01'), 0.2)"
    }
   ]
  },
  {
   "title": "Google hits",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 12 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "scale(seriesByTag('name=requests.count', 'app=backend', 'server=backend_01'), 0.2)"
    }
   ]
  },
  {
   "title": "client side full page load",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByTags(summarize(seriesByTag('name=statsd.timers.ads_timer', 'app=fakesite', 'percentile='), '4min', 'average'), 'target')"
    }
   ]
  }
 ]
}